# Feature Engineering

For some definitions, handling outliers and missing values, scaling, and encoding may be considered feature engineering. Here we'll draw a distinction between data preparation, data preprocessing, and feature engineering.

- **data preparation**: the basic data cleaning necessary to get our data ready for exploration/analysis, e.g. correcting data types, fixing typos
- **data preprocessing**: further data transformation done for the sake of modeling, as oppsoed to exploration/analysis, e.g. scaling, imputing, encoding
- **feature engineering**: adding, combining, or removing features; usually with the help of domain knowledge

Feature engineering can happen as part of data exploration or modeling, and engineered featured are also commonly explored.

Some examples of feature engineering by this definition:

- domain-based conversion (example: farenheit to celsius, BMI calculation, log transformation)
- domain based cutoffs (example: age >= 18 = is_adult; also dates)

- add / subtract (example: zillow dataset: beds + baths = room_count; total_sqft - 200 * bedrooms - 40 * bathrooms = living_area)
- combine as booleans as a count (example: telco_churn: streaming + backups + ...  = service_count)
- multiply / divide (example: tips dataset: total_bill / size = price_per_person)
- ratios (example: tips dataset: tip / total_bill = tip percentage)

Simplify!

- categorical with many unique values to top 3 + "Other"
- categorical to boolean: pool count -> has pool
- continous -> categorical via binning (aka quantization or discretization) (example: income -> high, medium, low earner)

In this lesson we'll cover some *automated* **feature selection** methods, that is, methods for determining which features are the most important.

- SelectKBest
- Recursive Feature Elimination
- Sequential Feature Selection

In [8]:
mycols = ['col1', 'col2', 'col3', 'col4']

In [9]:
# # start with initializing empty lists
# # feature space will contain our features
# feature_space = []
# # scores will contain model performance
# scores = []
# # iterate through the list of columns:
# for col in mycols:
#     # add a new feature in each cycle
#     feature_space.append(col)
#     # fit a model based on the new feature space
#     model_object.fit(X[feature_space], y)
#     # get the score for that model
#     scores.append(model_object.score(X[feature_space], y))
    
# my_scores = dict(zip(feature_space, scores))

## Setup

In [10]:
import numpy as np
import pandas as pd
import ins_wrangle as wrangle
from sklearn.feature_selection import SelectKBest, RFE, f_regression, SequentialFeatureSelector

In [11]:
df = wrangle.wrangle_grades()

In [13]:
# train_validate, test = train_test_split(df)
# train, validate = train_test_split(train_validate)

train, validate, test = wrangle.split_data(df)

In [14]:
train.head(3)

student_id  exam1  exam2  exam3  final_grade
49          50     58     65     70           68
22          23     62     70     79           70
55          56     83     80     86           85

In [15]:
X_train, y_train = train[['exam1', 'exam2', 'exam3']], train.final_grade
X_validate, y_validate = validate[['exam1', 'exam2', 'exam3']], validate.final_grade
X_test, y_test = test[['exam1', 'exam2', 'exam3']], test.final_grade

## Select K Best

- looks at each feature in isolation against the target based on correlation
- fastest of all approaches covered in this lesson
- doesn't consider feature interactions
- After fitting: `.scores_`, `.pvalues_`, `.get_support()`, and `.transform`

In [16]:
# make the thing
kbest = SelectKBest(f_regression, k=2)
# fit the thing
_ = kbest.fit(X_train, y_train)

In [17]:
# statistical f-value:
kbest.scores_
#p value: 
kbest.pvalues_

array([8.63527707e-43, 5.98109882e-25, 1.42742809e-31])

In [18]:
kbest_results = pd.DataFrame(
    dict(p=kbest.pvalues_, f=kbest.scores_),
                             index = X_train.columns)

In [19]:
kbest_results

p            f
exam1  8.635277e-43  1743.869458
exam2  5.981099e-25   339.463277
exam3  1.427428e-31   637.289373

In [20]:
# get-support() will output a boolean mask to tell me which features were selected
# we can apply this mask to the columns in our original dataframe
X_train.columns[kbest.get_support()]

Index(['exam1', 'exam3'], dtype='object')

In [21]:
# kbest transform will convert our information to the selected feature subspace
# ****buuuuuut, its just a numpy array
kbest.transform(X_train)[:5]

array([[ 58,  70],
       [ 62,  79],
       [ 83,  86],
       [100,  95],
       [ 98,  96]])

In [22]:
X_train_transformed = pd.DataFrame(
    kbest.transform(X_train),
    columns=X_train.columns[kbest.get_support()],
    index=X_train.index
)

In [23]:
X_train_transformed.head(3)

exam1  exam3
49     58     70
22     62     79
55     83     86

## RFE

- Recursive Feature Elimination
- Progressively eliminate features based on importance to the model
- Requires a model with either a `.coef_` or `.feature_importances_` property
- After fitting: `.ranking_`, `.get_support()`, and `.transform()`

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
# make a model object to use in RFE process.
# The model is here to give us metrics on feature importance and model score
# allowing us to recursively reduce the number of features to reach our desired space
model = LinearRegression()

In [26]:
# make thing
rfe = RFE(model, n_features_to_select=2)
# fit thing
rfe.fit(X_train, y_train)

RFE(estimator=LinearRegression(), n_features_to_select=2)

In [27]:
rfe.ranking_

array([1, 2, 1])

In [28]:
pd.DataFrame(
{
    'rfe_ranking': rfe.ranking_
},index = X_train.columns)

rfe_ranking
exam1            1
exam2            2
exam3            1

In [29]:
rfe.get_support()

array([ True, False,  True])

In [30]:
X_train_transformed = pd.DataFrame(
rfe.transform(X_train),
index = X_train.index,
columns = X_train.columns[rfe.support_])

In [31]:
X_train_transformed.head()

exam1  exam3
49     58     70
22     62     79
55     83     86
91    100     95
79     98     96

## Sequential Feature Selector

- progressively adds features based on cross validated model performance
- forwards: start with 0, add the best additional feature until you have the desired number
- backwards: start with all features, remove the worst performing until you have the desired number
- After fitting: `.support_`, `.transform`

In [32]:
model = LinearRegression()
sfs = SequentialFeatureSelector(model, n_features_to_select=2)
sfs.fit(X_train, y_train)

SequentialFeatureSelector(estimator=LinearRegression(), n_features_to_select=2)

In [33]:
X_train_transformed = pd.DataFrame(
sfs.transform(X_train),
index = X_train.index,
columns = X_train.columns[sfs.support_])

In [34]:
X_train_transformed

exam1  exam3
49      58     70
22      62     79
55      83     86
91     100     95
79      98     96
40      98     96
101     58     70
97      92     94
9       62     79
52     100     95
103     70     78
98      73     75
73      70     78
12      70     78
86      70     78
59      73     75
92      98     96
34      70     78
33      73     75
84      92     94
81      83     86
13     100     95
31      79     85
88      58     70
70      79     85
61      62     79
74      62     79
14      98     96
26     100     95
7       73     75
37      57     75
6       92     94
43      93     96
27      98     96
54      85     87
30      93     96
18      79     85
53      98     96
69      93     96
67      85     87
17      93     96
15      85     87
29      83     86
78     100     95
48      62     79
3       83     86
99      70     78
44      79     85
11      57     75
72      73     75
45      92     94
47      70     78
64      70     78
96      79     85
62      58     70
36      58     70

## Conclusion

- Simpler models handle change + variability better
- Use RFE to narrow down your features and find the best ones, if your dataset is large (> 1GB; `df.info()`) use select k best instead
- Remember: feature engineering is much more than feature selection!